// <auto-generated />
using DSR.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DSR.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("DSR.Models.Armor", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<double>("BleedResistence")
                        .HasColumnType("double");

                    b.Property<double>("CurseResistence")
                        .HasColumnType("double");

                    b.Property<int>("Durability")
                        .HasColumnType("int");

                    b.Property<double>("FireProtection")
                        .HasColumnType("double");

                    b.Property<double>("LightningProtection")
                        .HasColumnType("double");

                    b.Property<double>("MagicProtection")
                        .HasColumnType("double");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<double>("PhysicalProtection")
                        .HasColumnType("double");

                    b.Property<double>("PoiseResistence")
                        .HasColumnType("double");

                    b.Property<double>("PoisonResistence")
                        .HasColumnType("double");

                    b.Property<double>("SlashProtection")
                        .HasColumnType("double");

                    b.Property<double>("StrikeProtection")
                        .HasColumnType("double");

                    b.Property<double>("ThrustProtection")
                        .HasColumnType("double");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<double>("Weight")
                        .HasColumnType("double");

                    b.HasKey("ID");

                    b.ToTable("Armors");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            BleedResistence = 8.0,
                            CurseResistence = 6.0,
                            Durability = 450,
                            FireProtection = 9.0,
                            LightningProtection = 6.0,
                            MagicProtection = 8.0,
                            Name = "Balder Helm",
                            PhysicalProtection = 14.0,
                            PoiseResistence = 0.0,
                            PoisonResistence = 8.0,
                            SlashProtection = 17.0,
                            StrikeProtection = 14.0,
                            ThrustProtection = 13.0,
                            Type = 1,
                            Weight = 4.2000000000000002
                        },
                        new
                        {
                            ID = 2,
                            BleedResistence = 15.0,
                            CurseResistence = 0.0,
                            Durability = 250,
                            FireProtection = 6.0,
                            LightningProtection = 6.0,
                            MagicProtection = 5.0,
                            Name = "Big Hat",
                            PhysicalProtection = 14.0,
                            PoiseResistence = 0.0,
                            PoisonResistence = 18.0,
                            SlashProtection = 15.4,
                            StrikeProtection = 15.4,
                            ThrustProtection = 12.6,
                            Type = 1,
                            Weight = 3.0
                        },
                        new
                        {
                            ID = 3,
                            BleedResistence = 15.0,
                            CurseResistence = 5.0,
                            Durability = 600,
                            FireProtection = 19.0,
                            LightningProtection = 8.0,
                            MagicProtection = 11.0,
                            Name = "Black Iron Helm",
                            PhysicalProtection = 27.0,
                            PoiseResistence = 12.0,
                            PoisonResistence = 10.0,
                            SlashProtection = 31.0,
                            StrikeProtection = 26.0,
                            ThrustProtection = 27.0,
                            Type = 1,
                            Weight = 6.0
                        },
                        new
                        {
                            ID = 4,
                            BleedResistence = 12.0,
                            CurseResistence = 0.0,
                            Durability = 550,
                            FireProtection = 18.0,
                            LightningProtection = 6.0,
                            MagicProtection = 11.0,
                            Name = "Black Knight Helm",
                            PhysicalProtection = 21.0,
                            PoiseResistence = 8.0,
                            PoisonResistence = 6.0,
                            SlashProtection = 23.699999999999999,
                            StrikeProtection = 19.899999999999999,
                            ThrustProtection = 20.600000000000001,
                            Type = 1,
                            Weight = 5.0
                        },
                        new
                        {
                            ID = 5,
                            BleedResistence = 12.0,
                            CurseResistence = 2.0,
                            Durability = 200,
                            FireProtection = 8.0,
                            LightningProtection = 8.0,
                            MagicProtection = 11.0,
                            Name = "Black Sorcerer Hat",
                            PhysicalProtection = 5.0,
                            PoiseResistence = 0.0,
                            PoisonResistence = 12.0,
                            SlashProtection = 6.0,
                            StrikeProtection = 5.0,
                            ThrustProtection = 5.0,
                            Type = 1,
                            Weight = 0.69999999999999996
                        },
                        new
                        {
                            ID = 6,
                            BleedResistence = 16.0,
                            CurseResistence = 10.0,
                            Durability = 150,
                            FireProtection = 9.0,
                            LightningProtection = 11.0,
                            MagicProtection = 17.0,
                            Name = "Bloated Head",
                            PhysicalProtection = 17.0,
                            PoiseResistence = 0.0,
                            PoisonResistence = 32.0,
                            SlashProtection = 17.0,
                            StrikeProtection = 17.0,
                            ThrustProtection = 17.0,
                            Type = 1,
                            Weight = 2.5
                        },
                        new
                        {
                            ID = 7,
                            BleedResistence = 8.0,
                            CurseResistence = 15.0,
                            Durability = 150,
                            FireProtection = 9.0,
                            LightningProtection = 13.0,
                            MagicProtection = 22.0,
                            Name = "Bloated Sorcerer Head",
                            PhysicalProtection = 14.0,
                            PoiseResistence = 0.0,
                            PoisonResistence = 38.0,
                            SlashProtection = 14.0,
                            StrikeProtection = 14.0,
                            ThrustProtection = 14.0,
                            Type = 1,
                            Weight = 2.2000000000000002
                        },
                        new
                        {
                            ID = 8,
                            BleedResistence = 11.0,
                            CurseResistence = 6.0,
                            Durability = 600,
                            FireProtection = 11.0,
                            LightningProtection = 11.0,
                            MagicProtection = 12.0,
                            Name = "Brass Helm",
                            PhysicalProtection = 22.0,
                            PoiseResistence = 8.0,
                            PoisonResistence = 9.0,
                            SlashProtection = 24.899999999999999,
                            StrikeProtection = 21.100000000000001,
                            ThrustProtection = 22.0,
                            Type = 1,
                            Weight = 5.0999999999999996
                        },
                        new
                        {
                            ID = 9,
                            BleedResistence = 8.0,
                            CurseResistence = 0.0,
                            Durability = 200,
                            FireProtection = 5.0,
                            LightningProtection = 6.0,
                            MagicProtection = 8.0,
                            Name = "Brigand Hood",
                            PhysicalProtection = 9.0,
                            PoiseResistence = 0.0,
                            PoisonResistence = 8.0,
                            SlashProtection = 10.0,
                            StrikeProtection = 10.0,
                            ThrustProtection = 9.0,
                            Type = 1,
                            Weight = 1.2
                        },
                        new
                        {
                            ID = 10,
                            BleedResistence = 13.0,
                            CurseResistence = 0.0,
                            Durability = 400,
                            FireProtection = 13.0,
                            LightningProtection = 7.0,
                            MagicProtection = 12.0,
                            Name = "Catarina Helm",
                            PhysicalProtection = 22.0,
                            PoiseResistence = 8.0,
                            PoisonResistence = 9.0,
                            SlashProtection = 25.0,
                            StrikeProtection = 22.0,
                            ThrustProtection = 22.0,
                            Type = 1,
                            Weight = 4.5
                        },
                        new
                        {
                            ID = 11,
                            BleedResistence = 10.0,
                            CurseResistence = 0.0,
                            Durability = 300,
                            FireProtection = 8.0,
                            LightningProtection = 3.0,
                            MagicProtection = 10.0,
                            Name = "Chain Helm",
                            PhysicalProtection = 12.0,
                            PoiseResistence = 5.0,
                            PoisonResistence = 6.0,
                            SlashProtection = 14.4,
                            StrikeProtection = 12.0,
                            ThrustProtection = 11.6,
                            Type = 1,
                            Weight = 3.0
                        },
                        new
                        {
                            ID = 12,
                            BleedResistence = 12.6,
                            CurseResistence = 0.0,
                            Durability = 500,
                            FireProtection = 19.399999999999999,
                            LightningProtection = 14.5,
                            MagicProtection = 21.800000000000001,
                            Name = "Cleric Helm",
                            PhysicalProtection = 36.299999999999997,
                            PoiseResistence = 8.0,
                            PoisonResistence = 8.4000000000000004,
                            SlashProtection = 41.700000000000003,
                            StrikeProtection = 36.299999999999997,
                            ThrustProtection = 36.299999999999997,
                            Type = 1,
                            Weight = 4.7999999999999998
                        },
                        new
                        {
                            ID = 13,
                            BleedResistence = 5.0,
                            CurseResistence = 20.0,
                            Durability = 150,
                            FireProtection = 2.0,
                            LightningProtection = 6.0,
                            MagicProtection = 11.0,
                            Name = "Crown of Dusk",
                            PhysicalProtection = 5.0,
                            PoiseResistence = 0.0,
                            PoisonResistence = 5.0,
                            SlashProtection = 5.0,
                            StrikeProtection = 5.0,
                            ThrustProtection = 5.0,
                            Type = 1,
                            Weight = 0.40000000000000002
                        },
                        new
                        {
                            ID = 14,
                            BleedResistence = 9.0,
                            CurseResistence = 12.0,
                            Durability = 300,
                            FireProtection = 6.0,
                            LightningProtection = 6.0,
                            MagicProtection = 12.0,
                            Name = "Crown of the Dark Sun",
                            PhysicalProtection = 12.0,
                            PoiseResistence = 0.0,
                            PoisonResistence = 9.0,
                            SlashProtection = 12.0,
                            StrikeProtection = 12.0,
                            ThrustProtection = 12.0,
                            Type = 1,
                            Weight = 3.0
                        },
                        new
                        {
                            ID = 15,
                            BleedResistence = 15.0,
                            CurseResistence = 20.0,
                            Durability = 900,
                            FireProtection = 21.0,
                            LightningProtection = 21.0,
                            MagicProtection = 16.0,
                            Name = "Crown of the Great Lord",
                            PhysicalProtection = 16.0,
                            PoiseResistence = 0.0,
                            PoisonResistence = 8.0,
                            SlashProtection = 18.399999999999999,
                            StrikeProtection = 17.300000000000001,
                            ThrustProtection = 14.699999999999999,
                            Type = 1,
                            Weight = 3.0
                        },
                        new
                        {
                            ID = 16,
                            BleedResistence = 6.0,
                            CurseResistence = 0.0,
                            Durability = 150,
                            FireProtection = 6.0,
                            LightningProtection = 2.0,
                            MagicProtection = 8.0,
                            Name = "Crystalline Helm",
                            PhysicalProtection = 11.0,
                            PoiseResistence = 6.0,
                            PoisonResistence = 0.0,
                            SlashProtection = 13.0,
                            StrikeProtection = 9.0,
                            ThrustProtection = 11.0,
                            Type = 1,
                            Weight = 4.2000000000000002
                        },
                        new
                        {
                            ID = 17,
                            BleedResistence = 12.0,
                            CurseResistence = 0.0,
                            Durability = 300,
                            FireProtection = 12.0,
                            LightningProtection = 10.0,
                            MagicProtection = 12.0,
                            Name = "Dark Mask",
                            PhysicalProtection = 18.0,
                            PoiseResistence = 6.0,
                            PoisonResistence = 8.0,
                            SlashProtection = 19.800000000000001,
                            StrikeProtection = 18.0,
                            ThrustProtection = 16.899999999999999,
                            Type = 1,
                            Weight = 3.7999999999999998
                        },
                        new
                        {
                            ID = 18,
                            BleedResistence = 9.0,
                            CurseResistence = 9.0,
                            Durability = 150,
                            FireProtection = 5.0,
                            LightningProtection = 6.0,
                            MagicProtection = 8.0,
                            Name = "Dingy Hood",
                            PhysicalProtection = 6.0,
                            PoiseResistence = 0.0,
                            PoisonResistence = 7.0,
                            SlashProtection = 6.0,
                            StrikeProtection = 8.0,
                            ThrustProtection = 6.0,
                            Type = 1,
                            Weight = 0.80000000000000004
                        },
                        new
                        {
                            ID = 19,
                            BleedResistence = 15.0,
                            CurseResistence = 0.0,
                            Durability = 450,
                            FireProtection = 12.0,
                            LightningProtection = 7.0,
                            MagicProtection = 6.0,
                            Name = "Eastern Helm",
                            PhysicalProtection = 17.0,
                            PoiseResistence = 8.0,
                            PoisonResistence = 11.0,
                            SlashProtection = 21.0,
                            StrikeProtection = 16.0,
                            ThrustProtection = 16.0,
                            Type = 1,
                            Weight = 4.7000000000000002
                        },
                        new
                        {
                            ID = 20,
                            BleedResistence = 9.0,
                            CurseResistence = 0.0,
                            Durability = 450,
                            FireProtection = 9.0,
                            LightningProtection = 6.0,
                            MagicProtection = 9.0,
                            Name = "Elite Knight Helm",
                            PhysicalProtection = 17.0,
                            PoiseResistence = 8.0,
                            PoisonResistence = 6.0,
                            SlashProtection = 21.0,
                            StrikeProtection = 16.0,
                            ThrustProtection = 17.0,
                            Type = 1,
                            Weight = 4.5
                        },
                        new
                        {
                            ID = 21,
                            BleedResistence = 13.0,
                            CurseResistence = 0.0,
                            Durability = 600,
                            FireProtection = 4.0,
                            LightningProtection = 4.0,
                            MagicProtection = 5.0,
                            Name = "Fang Boar Helm",
                            PhysicalProtection = 26.0,
                            PoiseResistence = 12.0,
                            PoisonResistence = 8.0,
                            SlashProtection = 31.199999999999999,
                            StrikeProtection = 23.399999999999999,
                            ThrustProtection = 26.0,
                            Type = 1,
                            Weight = 8.0
                        },
                        new
                        {
                            ID = 22,
                            BleedResistence = 22.0,
                            CurseResistence = 0.0,
                            Durability = 200,
                            FireProtection = 15.0,
                            LightningProtection = 15.0,
                            MagicProtection = 15.0,
                            Name = "Gargoyle Helm",
                            PhysicalProtection = 15.0,
                            PoiseResistence = 8.0,
                            PoisonResistence = 19.0,
                            SlashProtection = 19.100000000000001,
                            StrikeProtection = 12.300000000000001,
                            ThrustProtection = 13.699999999999999,
                            Type = 1,
                            Weight = 3.5
                        },
                        new
                        {
                            ID = 23,
                            BleedResistence = 13.0,
                            CurseResistence = 0.0,
                            Durability = 600,
                            FireProtection = 19.0,
                            LightningProtection = 13.0,
                            MagicProtection = 13.0,
                            Name = "Giant Helm",
                            PhysicalProtection = 27.0,
                            PoiseResistence = 14.0,
                            PoisonResistence = 8.0,
                            SlashProtection = 30.5,
                            StrikeProtection = 24.800000000000001,
                            ThrustProtection = 27.0,
                            Type = 1,
                            Weight = 6.2999999999999998
                        },
                        new
                        {
                            ID = 24,
                            BleedResistence = 16.0,
                            CurseResistence = 0.0,
                            Durability = 400,
                            FireProtection = 22.0,
                            LightningProtection = 8.0,
                            MagicProtection = 15.0,
                            Name = "Gold-Hemmed Black Hood",
                            PhysicalProtection = 11.0,
                            PoiseResistence = 0.0,
                            PoisonResistence = 36.0,
                            SlashProtection = 11.0,
                            StrikeProtection = 11.800000000000001,
                            ThrustProtection = 11.0,
                            Type = 1,
                            Weight = 1.3999999999999999
                        },
                        new
                        {
                            ID = 25,
                            BleedResistence = 17.0,
                            CurseResistence = 0.0,
                            Durability = 700,
                            FireProtection = 16.0,
                            LightningProtection = 6.0,
                            MagicProtection = 17.0,
                            Name = "Golem Helm",
                            PhysicalProtection = 35.0,
                            PoiseResistence = 13.0,
                            PoisonResistence = 12.0,
                            SlashProtection = 40.899999999999999,
                            StrikeProtection = 32.200000000000003,
                            ThrustProtection = 35.0,
                            Type = 1,
                            Weight = 6.2999999999999998
                        },
                        new
                        {
                            ID = 26,
                            BleedResistence = 11.0,
                            CurseResistence = 0.0,
                            Durability = 450,
                            FireProtection = 21.0,
                            LightningProtection = 11.0,
                            MagicProtection = 14.0,
                            Name = "Gough's Helm",
                            PhysicalProtection = 25.0,
                            PoiseResistence = 9.0,
                            PoisonResistence = 6.0,
                            SlashProtection = 26.199999999999999,
                            StrikeProtection = 25.0,
                            ThrustProtection = 23.800000000000001,
                            Type = 1,
                            Weight = 6.5
                        },
                        new
                        {
                            ID = 27,
                            BleedResistence = 17.0,
                            CurseResistence = 0.0,
                            Durability = 800,
                            FireProtection = 19.0,
                            LightningProtection = 23.0,
                            MagicProtection = 23.0,
                            Name = "Guardian Helm",
                            PhysicalProtection = 41.0,
                            PoiseResistence = 15.0,
                            PoisonResistence = 6.0,
                            SlashProtection = 47.100000000000001,
                            StrikeProtection = 38.5,
                            ThrustProtection = 41.0,
                            Type = 1,
                            Weight = 7.2000000000000002
                        },
                        new
                        {
                            ID = 28,
                            BleedResistence = 18.0,
                            CurseResistence = 9.0,
                            Durability = 900,
                            FireProtection = 22.0,
                            LightningProtection = 18.0,
                            MagicProtection = 22.0,
                            Name = "Havel's Helm",
                            PhysicalProtection = 36.0,
                            PoiseResistence = 18.0,
                            PoisonResistence = 4.0,
                            SlashProtection = 41.399999999999999,
                            StrikeProtection = 30.600000000000001,
                            ThrustProtection = 36.0,
                            Type = 1,
                            Weight = 7.5
                        },
                        new
                        {
                            ID = 29,
                            BleedResistence = 9.0,
                            CurseResistence = 6.0,
                            Durability = 600,
                            FireProtection = 19.0,
                            LightningProtection = 9.0,
                            MagicProtection = 9.0,
                            Name = "Helm of Artorias",
                            PhysicalProtection = 18.0,
                            PoiseResistence = 9.0,
                            PoisonResistence = 9.0,
                            SlashProtection = 20.699999999999999,
                            StrikeProtection = 16.199999999999999,
                            ThrustProtection = 18.899999999999999,
                            Type = 1,
                            Weight = 4.2000000000000002
                        },
                        new
                        {
                            ID = 30,
                            BleedResistence = 11.0,
                            CurseResistence = 5.0,
                            Durability = 500,
                            FireProtection = 11.0,
                            LightningProtection = 7.0,
                            MagicProtection = 10.0,
                            Name = "Helm of Favor",
                            PhysicalProtection = 18.0,
                            PoiseResistence = 8.0,
                            PoisonResistence = 8.0,
                            SlashProtection = 20.899999999999999,
                            StrikeProtection = 17.100000000000001,
                            ThrustProtection = 18.0,
                            Type = 1,
                            Weight = 4.5
                        },
                        new
                        {
                            ID = 31,
                            BleedResistence = 10.0,
                            CurseResistence = 0.0,
                            Durability = 250,
                            FireProtection = 12.0,
                            LightningProtection = 8.0,
                            MagicProtection = 10.0,
                            Name = "Helm of Thorns",
                            PhysicalProtection = 17.0,
                            PoiseResistence = 8.0,
                            PoisonResistence = 7.0,
                            SlashProtection = 18.5,
                            StrikeProtection = 16.100000000000001,
                            ThrustProtection = 17.0,
                            Type = 1,
                            Weight = 4.0999999999999996
                        },
                        new
                        {
                            ID = 32,
                            BleedResistence = 11.0,
                            CurseResistence = 18.0,
                            Durability = 500,
                            FireProtection = 13.0,
                            LightningProtection = 10.0,
                            MagicProtection = 12.0,
                            Name = "Helm of the Wise",
                            PhysicalProtection = 19.0,
                            PoiseResistence = 8.0,
                            PoisonResistence = 7.0,
                            SlashProtection = 20.699999999999999,
                            StrikeProtection = 17.100000000000001,
                            ThrustProtection = 18.0,
                            Type = 1,
                            Weight = 5.0999999999999996
                        },
                        new
                        {
                            ID = 33,
                            BleedResistence = 7.0,
                            CurseResistence = 0.0,
                            Durability = 200,
                            FireProtection = 6.0,
                            LightningProtection = 4.0,
                            MagicProtection = 6.0,
                            Name = "Hollow Soldier Helm",
                            PhysicalProtection = 10.0,
                            PoiseResistence = 5.0,
                            PoisonResistence = 5.0,
                            SlashProtection = 11.1,
                            StrikeProtection = 10.0,
                            ThrustProtection = 8.8000000000000007,
                            Type = 1,
                            Weight = 3.0
                        },
                        new
                        {
                            ID = 34,
                            BleedResistence = 9.0,
                            CurseResistence = 0.0,
                            Durability = 250,
                            FireProtection = 9.0,
                            LightningProtection = 6.0,
                            MagicProtection = 9.0,
                            Name = "Hollow Thief's Hood",
                            PhysicalProtection = 17.0,
                            PoiseResistence = 8.0,
                            PoisonResistence = 6.0,
                            SlashProtection = 21.0,
                            StrikeProtection = 16.0,
                            ThrustProtection = 17.0,
                            Type = 1,
                            Weight = 1.1000000000000001
                        },
                        new
                        {
                            ID = 35,
                            BleedResistence = 5.0,
                            CurseResistence = 0.0,
                            Durability = 250,
                            FireProtection = 5.0,
                            LightningProtection = 6.0,
                            MagicProtection = 6.0,
                            Name = "Hollow Warrior Helm",
                            PhysicalProtection = 10.0,
                            PoiseResistence = 3.0,
                            PoisonResistence = 5.0,
                            SlashProtection = 10.300000000000001,
                            StrikeProtection = 9.6999999999999993,
                            ThrustProtection = 9.5,
                            Type = 1,
                            Weight = 2.6000000000000001
                        },
                        new
                        {
                            ID = 36,
                            BleedResistence = 8.0,
                            CurseResistence = 2.0,
                            Durability = 350,
                            FireProtection = 10.0,
                            LightningProtection = 9.0,
                            MagicProtection = 10.0,
                            Name = "Iron Helm",
                            PhysicalProtection = 14.0,
                            PoiseResistence = 8.0,
                            PoisonResistence = 12.0,
                            SlashProtection = 14.0,
                            StrikeProtection = 14.0,
                            ThrustProtection = 13.699999999999999,
                            Type = 1,
                            Weight = 4.5
                        },
                        new
                        {
                            ID = 37,
                            BleedResistence = 9.0,
                            CurseResistence = 0.0,
                            Durability = 400,
                            FireProtection = 9.0,
                            LightningProtection = 5.0,
                            MagicProtection = 8.0,
                            Name = "Knight Helm",
                            PhysicalProtection = 14.0,
                            PoiseResistence = 8.0,
                            PoisonResistence = 6.0,
                            SlashProtection = 16.0,
                            StrikeProtection = 13.0,
                            ThrustProtection = 14.0,
                            Type = 1,
                            Weight = 4.2000000000000002
                        },
                        new
                        {
                            ID = 38,
                            BleedResistence = 9.0,
                            CurseResistence = 3.0,
                            Durability = 150,
                            FireProtection = 5.0,
                            LightningProtection = 6.0,
                            MagicProtection = 8.0,
                            Name = "Maiden Hood",
                            PhysicalProtection = 7.0,
                            PoiseResistence = 0.0,
                            PoisonResistence = 7.0,
                            SlashProtection = 7.0,
                            StrikeProtection = 8.1999999999999993,
                            ThrustProtection = 7.0,
                            Type = 1,
                            Weight = 0.80000000000000004
                        },
                        new
                        {
                            ID = 39,
                            BleedResistence = 9.0,
                            CurseResistence = 20.0,
                            Durability = 400,
                            FireProtection = 10.0,
                            LightningProtection = 7.0,
                            MagicProtection = 12.0,
                            Name = "Mask of Velka",
                            PhysicalProtection = 12.0,
                            PoiseResistence = 0.0,
                            PoisonResistence = 9.0,
                            SlashProtection = 12.0,
                            StrikeProtection = 13.0,
                            ThrustProtection = 12.0,
                            Type = 1,
                            Weight = 2.5
                        },
                        new
                        {
                            ID = 40,
                            BleedResistence = 6.0,
                            CurseResistence = 0.0,
                            Durability = 200,
                            FireProtection = 8.0,
                            LightningProtection = 10.0,
                            MagicProtection = 10.0,
                            Name = "Mask of the Child",
                            PhysicalProtection = 6.0,
                            PoiseResistence = 0.0,
                            PoisonResistence = 0.0,
                            SlashProtection = 6.0,
                            StrikeProtection = 6.0,
                            ThrustProtection = 6.0,
                            Type = 1,
                            Weight = 1.2
                        },
                        new
                        {
                            ID = 41,
                            BleedResistence = 6.0,
                            CurseResistence = 0.0,
                            Durability = 200,
                            FireProtection = 6.0,
                            LightningProtection = 8.0,
                            MagicProtection = 10.0,
                            Name = "Mask of the Father",
                            PhysicalProtection = 6.0,
                            PoiseResistence = 0.0,
                            PoisonResistence = 0.0,
                            SlashProtection = 6.0,
                            StrikeProtection = 6.0,
                            ThrustProtection = 6.0,
                            Type = 1,
                            Weight = 1.2
                        },
                        new
                        {
                            ID = 42,
                            BleedResistence = 10.0,
                            CurseResistence = 0.0,
                            Durability = 200,
                            FireProtection = 6.0,
                            LightningProtection = 8.0,
                            MagicProtection = 12.0,
                            Name = "Mask of the Mother",
                            PhysicalProtection = 6.0,
                            PoiseResistence = 0.0,
                            PoisonResistence = 0.0,
                            SlashProtection = 6.0,
                            StrikeProtection = 6.0,
                            ThrustProtection = 6.0,
                            Type = 1,
                            Weight = 1.2
                        },
                        new
                        {
                            ID = 43,
                            BleedResistence = 8.0,
                            CurseResistence = 8.0,
                            Durability = 400,
                            FireProtection = 7.0,
                            LightningProtection = 9.0,
                            MagicProtection = 12.0,
                            Name = "Mask of the Sealer",
                            PhysicalProtection = 12.0,
                            PoiseResistence = 0.0,
                            PoisonResistence = 8.0,
                            SlashProtection = 12.0,
                            StrikeProtection = 13.0,
                            ThrustProtection = 12.0,
                            Type = 1,
                            Weight = 1.5
                        },
                        new
                        {
                            ID = 44,
                            BleedResistence = 18.0,
                            CurseResistence = 8.0,
                            Durability = 700,
                            FireProtection = 6.0,
                            LightningProtection = 6.0,
                            MagicProtection = 5.0,
                            Name = "Ornstein's Helm",
                            PhysicalProtection = 32.0,
                            PoiseResistence = 9.0,
                            PoisonResistence = 8.0,
                            SlashProtection = 36.200000000000003,
                            StrikeProtection = 30.399999999999999,
                            ThrustProtection = 32.0,
                            Type = 1,
                            Weight = 5.5
                        },
                        new
                        {
                            ID = 45,
                            BleedResistence = 12.0,
                            CurseResistence = 0.0,
                            Durability = 150,
                            FireProtection = 11.0,
                            LightningProtection = 8.0,
                            MagicProtection = 31.0,
                            Name = "Painting Guardian Hood",
                            PhysicalProtection = 3.0,
                            PoiseResistence = 0.0,
                            PoisonResistence = 30.0,
                            SlashProtection = 3.0,
                            StrikeProtection = 3.6000000000000001,
                            ThrustProtection = 3.0,
                            Type = 1,
                            Weight = 0.59999999999999998
                        },
                        new
                        {
                            ID = 46,
                            BleedResistence = 13.0,
                            CurseResistence = 22.0,
                            Durability = 500,
                            FireProtection = 13.0,
                            LightningProtection = 7.0,
                            MagicProtection = 12.0,
                            Name = "Paladin Helm",
                            PhysicalProtection = 22.0,
                            PoiseResistence = 8.0,
                            PoisonResistence = 9.0,
                            SlashProtection = 25.300000000000001,
                            StrikeProtection = 20.899999999999999,
                            ThrustProtection = 22.0,
                            Type = 1,
                            Weight = 5.0
                        },
                        new
                        {
                            ID = 47,
                            BleedResistence = 6.0,
                            CurseResistence = 0.0,
                            Durability = 250,
                            FireProtection = 7.0,
                            LightningProtection = 7.0,
                            MagicProtection = 5.0,
                            Name = "Pharis's Hat",
                            PhysicalProtection = 7.0,
                            PoiseResistence = 0.0,
                            PoisonResistence = 5.0,
                            SlashProtection = 7.0,
                            StrikeProtection = 7.0,
                            ThrustProtection = 7.0,
                            Type = 1,
                            Weight = 1.2
                        },
                        new
                        {
                            ID = 48,
                            BleedResistence = 11.0,
                            CurseResistence = 11.0,
                            Durability = 250,
                            FireProtection = 12.0,
                            LightningProtection = 8.0,
                            MagicProtection = 10.0,
                            Name = "Porcelain Mask",
                            PhysicalProtection = 13.0,
                            PoiseResistence = 3.0,
                            PoisonResistence = 19.0,
                            SlashProtection = 13.6,
                            StrikeProtection = 13.0,
                            ThrustProtection = 14.300000000000001,
                            Type = 1,
                            Weight = 2.5
                        },
                        new
                        {
                            ID = 49,
                            BleedResistence = 9.0,
                            CurseResistence = 0.0,
                            Durability = 350,
                            FireProtection = 5.0,
                            LightningProtection = 7.0,
                            MagicProtection = 9.0,
                            Name = "Priest's Hat",
                            PhysicalProtection = 9.0,
                            PoiseResistence = 0.0,
                            PoisonResistence = 8.0,
                            SlashProtection = 8.0,
                            StrikeProtection = 9.4000000000000004,
                            ThrustProtection = 8.0,
                            Type = 1,
                            Weight = 1.2
                        },
                        new
                        {
                            ID = 50,
                            BleedResistence = 16.0,
                            CurseResistence = 0.0,
                            Durability = 500,
                            FireProtection = 10.0,
                            LightningProtection = 6.0,
                            MagicProtection = 10.0,
                            Name = "Royal Helm",
                            PhysicalProtection = 16.0,
                            PoiseResistence = 8.0,
                            PoisonResistence = 12.0,
                            SlashProtection = 16.0,
                            StrikeProtection = 13.9,
                            ThrustProtection = 16.0,
                            Type = 1,
                            Weight = 4.5
                        },
                        new
                        {
                            ID = 51,
                            BleedResistence = 12.0,
                            CurseResistence = 0.0,
                            Durability = 150,
                            FireProtection = 8.0,
                            LightningProtection = 4.0,
                            MagicProtection = 6.0,
                            Name = "Sack",
                            PhysicalProtection = 6.0,
                            PoiseResistence = 0.0,
                            PoisonResistence = 10.0,
                            SlashProtection = 6.0,
                            StrikeProtection = 10.0,
                            ThrustProtection = 5.0,
                            Type = 1,
                            Weight = 0.59999999999999998
                        },
                        new
                        {
                            ID = 52,
                            BleedResistence = 15.0,
                            CurseResistence = 0.0,
                            Durability = 200,
                            FireProtection = 6.0,
                            LightningProtection = 6.0,
                            MagicProtection = 5.0,
                            Name = "Shadow Mask",
                            PhysicalProtection = 9.0,
                            PoiseResistence = 0.0,
                            PoisonResistence = 18.0,
                            SlashProtection = 9.0,
                            StrikeProtection = 9.9000000000000004,
                            ThrustProtection = 9.0,
                            Type = 1,
                            Weight = 0.90000000000000002
                        },
                        new
                        {
                            ID = 53,
                            BleedResistence = 9.0,
                            CurseResistence = 1.0,
                            Durability = 600,
                            FireProtection = 11.0,
                            LightningProtection = 14.0,
                            MagicProtection = 10.0,
                            Name = "Silver Knight Helm",
                            PhysicalProtection = 21.0,
                            PoiseResistence = 8.0,
                            PoisonResistence = 5.0,
                            SlashProtection = 24.100000000000001,
                            StrikeProtection = 19.699999999999999,
                            ThrustProtection = 20.600000000000001,
                            Type = 1,
                            Weight = 4.7999999999999998
                        },
                        new
                        {
                            ID = 54,
                            BleedResistence = 15.0,
                            CurseResistence = 0.0,
                            Durability = 300,
                            FireProtection = 17.0,
                            LightningProtection = 13.0,
                            MagicProtection = 18.0,
                            Name = "Six-Eyed Helm of the Channelers",
                            PhysicalProtection = 20.0,
                            PoiseResistence = 5.0,
                            PoisonResistence = 13.0,
                            SlashProtection = 22.800000000000001,
                            StrikeProtection = 19.199999999999999,
                            ThrustProtection = 20.0,
                            Type = 1,
                            Weight = 3.8999999999999999
                        },
                        new
                        {
                            ID = 55,
                            BleedResistence = 21.0,
                            CurseResistence = 5.0,
                            Durability = 700,
                            FireProtection = 26.0,
                            LightningProtection = 21.0,
                            MagicProtection = 19.0,
                            Name = "Smough's Helm",
                            PhysicalProtection = 40.0,
                            PoiseResistence = 14.0,
                            PoisonResistence = 12.0,
                            SlashProtection = 46.0,
                            StrikeProtection = 34.799999999999997,
                            ThrustProtection = 40.0,
                            Type = 1,
                            Weight = 6.7999999999999998
                        },
                        new
                        {
                            ID = 56,
                            BleedResistence = 19.0,
                            CurseResistence = 0.0,
                            Durability = 300,
                            FireProtection = 9.0,
                            LightningProtection = 12.0,
                            MagicProtection = 13.0,
                            Name = "Snickering Top Hat",
                            PhysicalProtection = 12.0,
                            PoiseResistence = 0.0,
                            PoisonResistence = 14.0,
                            SlashProtection = 12.0,
                            StrikeProtection = 16.199999999999999,
                            ThrustProtection = 12.0,
                            Type = 1,
                            Weight = 2.0
                        },
                        new
                        {
                            ID = 57,
                            BleedResistence = 6.0,
                            CurseResistence = 0.0,
                            Durability = 200,
                            FireProtection = 5.0,
                            LightningProtection = 6.0,
                            MagicProtection = 10.0,
                            Name = "Sorcerer Hat",
                            PhysicalProtection = 8.0,
                            PoiseResistence = 0.0,
                            PoisonResistence = 5.0,
                            SlashProtection = 8.0,
                            StrikeProtection = 9.0,
                            ThrustProtection = 8.0,
                            Type = 1,
                            Weight = 1.2
                        },
                        new
                        {
                            ID = 58,
                            BleedResistence = 9.0,
                            CurseResistence = 0.0,
                            Durability = 250,
                            FireProtection = 8.0,
                            LightningProtection = 3.0,
                            MagicProtection = 8.0,
                            Name = "Standard Helm",
                            PhysicalProtection = 14.0,
                            PoiseResistence = 5.0,
                            PoisonResistence = 8.0,
                            SlashProtection = 16.0,
                            StrikeProtection = 8.0,
                            ThrustProtection = 14.0,
                            Type = 1,
                            Weight = 3.5
                        },
                        new
                        {
                            ID = 59,
                            BleedResistence = 9.0,
                            CurseResistence = 0.0,
                            Durability = 500,
                            FireProtection = 8.0,
                            LightningProtection = 5.0,
                            MagicProtection = 8.0,
                            Name = "Steel Helm",
                            PhysicalProtection = 16.0,
                            PoiseResistence = 9.0,
                            PoisonResistence = 6.0,
                            SlashProtection = 18.399999999999999,
                            StrikeProtection = 15.0,
                            ThrustProtection = 16.0,
                            Type = 1,
                            Weight = 5.4000000000000004
                        },
                        new
                        {
                            ID = 60,
                            BleedResistence = 17.0,
                            CurseResistence = 0.0,
                            Durability = 800,
                            FireProtection = 21.0,
                            LightningProtection = 21.0,
                            MagicProtection = 17.0,
                            Name = "Stone Helm",
                            PhysicalProtection = 35.0,
                            PoiseResistence = 15.0,
                            PoisonResistence = 6.0,
                            SlashProtection = 40.299999999999997,
                            StrikeProtection = 32.899999999999999,
                            ThrustProtection = 35.0,
                            Type = 1,
                            Weight = 6.7999999999999998
                        },
                        new
                        {
                            ID = 61,
                            BleedResistence = 0.0,
                            CurseResistence = 0.0,
                            Durability = 80,
                            FireProtection = 24.0,
                            LightningProtection = 13.0,
                            MagicProtection = 5.0,
                            Name = "Sunlight Maggot",
                            PhysicalProtection = 6.0,
                            PoiseResistence = 0.0,
                            PoisonResistence = 0.0,
                            SlashProtection = 6.0,
                            StrikeProtection = 6.0,
                            ThrustProtection = 6.0,
                            Type = 1,
                            Weight = 1.3999999999999999
                        },
                        new
                        {
                            ID = 62,
                            BleedResistence = 10.0,
                            CurseResistence = 0.0,
                            Durability = 300,
                            FireProtection = 2.0,
                            LightningProtection = 2.0,
                            MagicProtection = 8.0,
                            Name = "Symbol of Avarice",
                            PhysicalProtection = 21.0,
                            PoiseResistence = 15.0,
                            PoisonResistence = 0.0,
                            SlashProtection = 21.0,
                            StrikeProtection = 10.9,
                            ThrustProtection = 21.0,
                            Type = 1,
                            Weight = 10.0
                        },
                        new
                        {
                            ID = 63,
                            BleedResistence = 9.0,
                            CurseResistence = 1.0,
                            Durability = 400,
                            FireProtection = 12.0,
                            LightningProtection = 6.0,
                            MagicProtection = 9.0,
                            Name = "Tattered Cloth Hood",
                            PhysicalProtection = 8.0,
                            PoiseResistence = 0.0,
                            PoisonResistence = 23.0,
                            SlashProtection = 8.0,
                            StrikeProtection = 8.9000000000000004,
                            ThrustProtection = 8.0,
                            Type = 1,
                            Weight = 1.1000000000000001
                        },
                        new
                        {
                            ID = 64,
                            BleedResistence = 9.0,
                            CurseResistence = 0.0,
                            Durability = 250,
                            FireProtection = 5.0,
                            LightningProtection = 6.0,
                            MagicProtection = 8.0,
                            Name = "Thief Mask",
                            PhysicalProtection = 9.0,
                            PoiseResistence = 0.0,
                            PoisonResistence = 12.0,
                            SlashProtection = 9.0,
                            StrikeProtection = 10.0,
                            ThrustProtection = 9.0,
                            Type = 1,
                            Weight = 1.2
                        },
                        new
                        {
                            ID = 65,
                            BleedResistence = 8.0,
                            CurseResistence = 0.0,
                            Durability = 400,
                            FireProtection = 9.0,
                            LightningProtection = 10.0,
                            MagicProtection = 8.0,
                            Name = "Wanderer Hood",
                            PhysicalProtection = 9.0,
                            PoiseResistence = 0.0,
                            PoisonResistence = 8.0,
                            SlashProtection = 10.0,
                            StrikeProtection = 10.0,
                            ThrustProtection = 9.0,
                            Type = 1,
                            Weight = 1.3999999999999999
                        },
                        new
                        {
                            ID = 66,
                            BleedResistence = 10.0,
                            CurseResistence = 11.0,
                            Durability = 250,
                            FireProtection = 6.0,
                            LightningProtection = 7.0,
                            MagicProtection = 12.0,
                            Name = "Witch Hat",
                            PhysicalProtection = 9.0,
                            PoiseResistence = 0.0,
                            PoisonResistence = 10.0,
                            SlashProtection = 9.0,
                            StrikeProtection = 10.0,
                            ThrustProtection = 9.0,
                            Type = 1,
                            Weight = 1.1000000000000001
                        },
                        new
                        {
                            ID = 67,
                            BleedResistence = 8.0,
                            CurseResistence = 35.0,
                            Durability = 400,
                            FireProtection = 3.0,
                            LightningProtection = 8.0,
                            MagicProtection = 15.0,
                            Name = "Xanthous Crown",
                            PhysicalProtection = 18.0,
                            PoiseResistence = 0.0,
                            PoisonResistence = 11.0,
                            SlashProtection = 18.0,
                            StrikeProtection = 28.0,
                            ThrustProtection = 15.0,
                            Type = 1,
                            Weight = 5.0
                        });
                });

            modelBuilder.Entity("DSR.Models.Weapon", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CriticalBonus")
                        .HasColumnType("int");

                    b.Property<int>("DexterityRequirement")
                        .HasColumnType("int");

                    b.Property<int>("DexterityScale")
                        .HasColumnType("int");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("DivineDamage")
                        .HasColumnType("int");

                    b.Property<int>("Durability")
                        .HasColumnType("int");

                    b.Property<int>("FaithRequirement")
                        .HasColumnType("int");

                    b.Property<int>("FaithScale")
                        .HasColumnType("int");

                    b.Property<int>("FireDamage")
                        .HasColumnType("int");

                    b.Property<int>("FireDefence")
                        .HasColumnType("int");

                    b.Property<int>("IntelligenceRequirement")
                        .HasColumnType("int");

                    b.Property<int>("IntelligenceScale")
                        .HasColumnType("int");

                    b.Property<int>("LightningDamage")
                        .HasColumnType("int");

                    b.Property<int>("LightningDefence")
                        .HasColumnType("int");

                    b.Property<int>("MagicalDamage")
                        .HasColumnType("int");

                    b.Property<int>("MagicalDefense")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<int>("OccultDamage")
                        .HasColumnType("int");

                    b.Property<int>("PhysicalDamage")
                        .HasColumnType("int");

                    b.Property<int>("PhysicalDefense")
                        .HasColumnType("int");

                    b.Property<int>("Stability")
                        .HasColumnType("int");

                    b.Property<int>("StrenghtRequirement")
                        .HasColumnType("int");

                    b.Property<int>("StrengthScale")
                        .HasColumnType("int");

                    b.Property<int>("UpgradePath")
                        .HasColumnType("int");

                    b.Property<double>("Weight")
                        .HasColumnType("double");

                    b.HasKey("ID");

                    b.ToTable("Weapons");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Weapon");
                });

            modelBuilder.Entity("DSR.Models.Shield", b =>
                {
                    b.HasBaseType("DSR.Models.Weapon");

                    b.HasDiscriminator().HasValue("Shield");
                });
#pragma warning restore 612, 618
        }
    }
}
